import { useEffect, useMemo, useState } from 'react';
import styles from './ActorPreflightLab.module.css';

type AnyRecord = Record<string, any>;
type Pairing = AnyRecord & { vibeKey: string; labels?: string[]; auditState?: string; verdict?: string; eligible?: boolean };
type Actor = AnyRecord & { actorId: string; canonicalName: string; romanizedName?: string; aliases?: string[]; pairings?: Pairing[] };
type Run = AnyRecord & { runId?: string; scope?: string; queryRuns?: AnyRecord[]; rawResults?: AnyRecord[]; rejections?: AnyRecord[]; identityEvidence?: AnyRecord; detectedEvents?: AnyRecord[]; strongestEvent?: AnyRecord; strongestCompiled?: AnyRecord; winner?: AnyRecord; alternate?: AnyRecord; curationReceipt?: AnyRecord };

const VERDICTS = ['approved','approved_override','needs_query_work','insufficient_material','identity_risk','do_not_schedule'];
const VERDICT_LABELS: Record<string, string> = { approved: 'Approved', approved_override: 'Approved with override', needs_query_work: 'Needs query work', insufficient_material: 'Insufficient material', identity_risk: 'Identity risk', do_not_schedule: 'Do not schedule' };
const api = async (body?: AnyRecord, query?: AnyRecord) => { const queryString = query ? `?${new URLSearchParams(Object.entries(query).filter(([,value]) => value !== undefined && value !== '') as [string,string][]).toString()}` : ''; const response = await fetch(`/.netlify/functions/actor-audits${queryString}`, { method: body ? 'POST' : 'GET', headers: body ? {'Content-Type':'application/json'} : undefined, body: body ? JSON.stringify(body) : undefined, credentials:'include' }); const result = await response.json().catch(() => null); if (!response.ok) throw new Error(result?.error || 'Actor audit desk unavailable.'); return result; };
const text = (value: unknown) => Array.isArray(value) ? value.join(' · ') : typeof value === 'object' && value ? JSON.stringify(value, null, 2) : String(value ?? '—');
const date = (value: unknown) => value ? new Date(String(value)).toLocaleString() : 'Not run';

export const ActorPreflightLab: React.FC = () => {
  const [actors,setActors] = useState<Actor[]>([]); const [actorId,setActorId] = useState(''); const [vibeKey,setVibeKey] = useState('');
  const [run,setRun] = useState<Run|null>(null); const [currentRun,setCurrentRun] = useState<Run|null>(null); const [loading,setLoading] = useState(true); const [busy,setBusy] = useState(''); const [notice,setNotice] = useState(''); const [railOpen,setRailOpen] = useState(true);
  const [scope,setScope] = useState('representative'); const [verdict,setVerdict] = useState(''); const [notes,setNotes] = useState(''); const [priorRuns,setPriorRuns] = useState<Run[]>([]);
  useEffect(() => { let live=true; api().then(result => { if(live) { const next = result.actors ?? []; setActors(next); if(next[0]) { setActorId(next[0].actorId); setVibeKey(next[0].pairings?.[0]?.vibeKey ?? ''); } } }).catch(e=>live&&setNotice(e.message)).finally(()=>live&&setLoading(false)); return()=>{live=false}; },[]);
  const actor = useMemo(()=>actors.find(item=>item.actorId===actorId),[actors,actorId]); const pairing = actor?.pairings?.find(item=>item.vibeKey===vibeKey);
  useEffect(() => { setRun(null); setCurrentRun(null); setPriorRuns([]); setVerdict(pairing?.verdict ?? ''); setNotes(pairing?.notes ?? ''); if(!actorId||!vibeKey)return; let live=true; api(undefined,{actorId,vibeKey}).then(result=>{if(live){setRun(result.currentRun ?? null); setCurrentRun(result.currentRun ?? null); setPriorRuns(result.priorRuns ?? []); setVerdict(result.verdict ?? ''); setNotes(result.notes ?? '');}}).catch(e=>live&&setNotice(e.message)); return()=>{live=false}; },[actorId,vibeKey,pairing?.verdict,pairing?.notes]);
  function applyRefresh(result:AnyRecord) { if (result.actors) setActors(result.actors); else if (result.actor) setActors(current => current.map(item => item.actorId === result.actor.actorId ? result.actor : item)); }
  async function startAudit(nextScope:string) { setBusy(nextScope); setNotice(''); try { const result=await api({action:'run',actorId,vibeKey,scope:nextScope}); applyRefresh(result); setRun(result.currentRun ?? null); setCurrentRun(result.currentRun ?? null); setPriorRuns(result.priorRuns ?? []); setVerdict(''); setNotes(''); setNotice(`${nextScope === 'full' ? 'Full' : 'Representative'} audit completed. Its pairing now needs a current verdict.`); } catch(e:any){setNotice(e.message)} finally{setBusy('')} }
  async function saveVerdict(event:React.FormEvent) { event.preventDefault(); if(!currentRun?.runId||run?.runId!==currentRun.runId||!verdict)return; setBusy('verdict'); setNotice(''); try { const result=await api({action:'verdict',actorId,vibeKey,runId:currentRun.runId,verdict,notes}); applyRefresh(result); setRun(result.currentRun ?? currentRun); setCurrentRun(result.currentRun ?? currentRun); setVerdict(result.verdict ?? verdict); setNotes(result.notes ?? notes); setNotice('Verdict saved to the curation ledger.'); } catch(e:any){setNotice(e.message)} finally{setBusy('')} }
  if(loading) return <div className={styles.empty}>Loading actor evidence desk…</div>;
  return <section className={styles.lab} aria-labelledby="actor-preflight-title">
    <header className={styles.masthead}><div><p className={styles.eyebrow}>Fandom Vibes / private calibration</p><h3 id="actor-preflight-title">Actor preflight lab</h3><p>Calibrate actor × Vibe Pack pairings against bounded evidence before they enter the Daily Drop rotation.</p></div><div className={styles.runbook}><span>Operator boundary</span><strong>One pairing at a time</strong><span>Every decision leaves a receipt.</span></div></header>
    {notice&&<div className={styles.error} role="status">{notice}</div>}
    <div className={`${styles.workspace} ${railOpen ? '' : styles.workspaceCollapsed}`}>
      <aside className={styles.rail} aria-label="Actor selector"><button className={styles.railToggle} type="button" aria-expanded={railOpen} aria-label={railOpen ? 'Collapse actor register' : 'Expand actor register'} onClick={()=>setRailOpen(open=>!open)}>{railOpen ? '‹' : '›'}</button><div className={styles.railHead}><strong>Actor register</strong><span>{actors.length} profiles · profile versions retained</span></div><div className={styles.actorList}>{actors.map(item=><button className={styles.actorButton} data-selected={item.actorId===actorId} key={item.actorId} onClick={()=>{setActorId(item.actorId);setVibeKey(item.pairings?.[0]?.vibeKey??'')}}><strong>{item.canonicalName}</strong><small>{item.romanizedName ?? item.actorId} · v{item.profileVersion ?? '—'}</small></button>)}</div></aside>
      <main className={styles.detail}>{!actor?<div className={styles.empty}>No actor profiles returned.</div>:<><section className={`${styles.panel} ${styles.detailPanel}`}><div className={styles.detailHead}><div><p className={styles.eyebrow}>Selected profile</p><h4>{actor.canonicalName}</h4><p>{actor.romanizedName} · aliases: {text(actor.aliases)}</p></div><span className={styles.muted}>Profile v{actor.profileVersion ?? '—'}</span></div><div className={styles.pairingStrip}>{(actor.pairings??[]).map(item=><button className={styles.pairing} data-selected={item.vibeKey===vibeKey} key={item.vibeKey} onClick={()=>setVibeKey(item.vibeKey)}><strong>{text(item.labels) || item.vibeKey}</strong><span className={styles.state} data-state={item.auditState}>{item.verdict ?? item.auditState ?? 'unreviewed'}</span><small>{item.queryCount ?? 0} queries · {date(item.lastRunAt)}</small></button>)}</div><div className={styles.controls}><button className={styles.buttonPrimary} disabled={!vibeKey||!!busy} onClick={()=>void startAudit(scope)}>{busy ? 'Running evidence pass…' : 'Run audit'}</button><select className={styles.select} value={scope} onChange={e=>setScope(e.target.value)} aria-label="Audit scope"><option value="representative">Representative scope</option><option value="full">Full scope</option></select><span className={styles.status}>{pairing?.eligible===false?'Not eligible for scheduling':'Eligible for review'}</span></div></section>
        <section className={styles.panel}><div className={styles.grid}><InfoCard title="Identity profile" data={actor} keys={['commonCollisions','representativeWorks','knownContamination','productStockMeanings','trustedSourcePatterns','problematicSourcePatterns']} /><RunEvidence run={run} currentRun={currentRun} priorRuns={priorRuns} onSelect={setRun}/></div>{run&&currentRun?.runId===run.runId?<form className={styles.verdict} onSubmit={saveVerdict}><label className={styles.label}>Editorial verdict<select className={styles.select} value={verdict} onChange={e=>setVerdict(e.target.value)} required><option value="">Choose a verdict</option>{VERDICTS.map(value=><option key={value} value={value}>{VERDICT_LABELS[value]}</option>)}</select></label><label className={styles.label}>Operator notes<textarea className={`${styles.input} ${styles.textarea}`} value={notes} maxLength={2000} onChange={e=>setNotes(e.target.value)} placeholder="What should the next operator know?" /></label><button className={styles.buttonPrimary} disabled={busy==='verdict'||!verdict}>Save verdict</button></form>:run?<p className={styles.historicalNotice}>This is a retained historical run. Return to the current run to revise scheduling eligibility.</p>:null}</section></>}</main>
    </div>
  </section>;
};

function InfoCard({title,data,keys}:{title:string;data:AnyRecord;keys:string[]}) { return <article className={`${styles.card} ${styles.cardWide}`}><h5>{title}</h5><div className={styles.grid}>{keys.map(key=><div key={key}><p className={styles.muted}>{key.replace(/[A-Z]/g,m=>` ${m}`).toUpperCase()}</p><div className={styles.chips}>{(Array.isArray(data[key])?data[key]:[data[key]]).filter(Boolean).map((item:any,index:number)=><span className={styles.chip} key={index}>{text(item)}</span>)}</div></div>)}</div></article>; }
function RunEvidence({run,currentRun,priorRuns,onSelect}:{run:Run|null;currentRun:Run|null;priorRuns:Run[];onSelect:(run:Run)=>void}) { const sections: Array<[string, unknown]>=[['Query ladder',run?.queryRuns],['Bounded raw results',run?.rawResults],['Rejection ledger',run?.rejections],['Identity evidence',run?.identityEvidence],['Detected event families',run?.detectedEvents],['Strongest Event board',run?.strongestEvent],['Strongest Compiled board',run?.strongestCompiled],['Winner',run?.winner],['Alternate',run?.alternate],['Curation receipt',run?.curationReceipt],['Operator verdict',run?.operatorVerdict]]; return <article className={`${styles.card} ${styles.cardWide}`}><h5>Audit evidence {run?.runId?`· ${run.runId}`:''}</h5>{run?<><p className={styles.muted}>{run.scope} scope · started {date(run.startedAt)} · completed {date(run.completedAt)} · {run.materialSufficient ? 'enough clean material' : 'insufficient clean material'}</p><div className={styles.evidence}>{sections.map(([label,value])=><details key={label}><summary>{label} <span className={styles.muted}>{Array.isArray(value)?`${value.length} records`:''}</span></summary><pre>{text(value)}</pre></details>)}</div></>:<p className={styles.empty}>Run an audit to open bounded queries, rejection codes, event boards, and the curation receipt.</p>}{currentRun&&<label className={styles.label}>Audit run<select className={styles.select} value={run?.runId ?? ''} onChange={e=>{const selected=[currentRun,...priorRuns].find(item=>item.runId===e.target.value);if(selected)onSelect(selected)}}><option value={currentRun.runId}>Current · {currentRun.runId} · {date(currentRun.completedAt)}</option>{priorRuns.map(item=><option key={item.runId} value={item.runId}>Retained · {item.runId} · {date(item.completedAt)}</option>)}</select></label>}</article>; }