// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/legendary-misprint/CertifiedMisprint.tsx": () => import("../components/mockups/legendary-misprint/CertifiedMisprint.tsx"),
  "./components/mockups/legendary-misprint/CollectorFoil.tsx": () => import("../components/mockups/legendary-misprint/CollectorFoil.tsx"),
  "./components/mockups/legendary-misprint/Current.tsx": () => import("../components/mockups/legendary-misprint/Current.tsx"),
  "./components/mockups/legendary-misprint/PrismaticRelic.tsx": () => import("../components/mockups/legendary-misprint/PrismaticRelic.tsx")
};
